spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect

telegram:
  bot:
    bot-username: ${bot.username}
    token: ${bot.token}
    admin-chat-id: ${bot.admin.chat.id}

user-preferences:
  admin-username: ${admin.username}
  admin-password: ${admin.password}
  contact-mobile-phone: ${admin.mobile.phone}
  working-hours:
    start: 8,0 # 08:00
    end: 23,0  # 23:00