name: Build on DockerHub and Deploy to Timeweb
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: ryhorkukharenkadev/instabox-bot:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}
      - name: Install SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Stop running container
        run: |
          ssh -o StrictHostKeyChecking=no username@your-timeweb-server 'sudo docker stop instabox-bot || true'
          ssh -o StrictHostKeyChecking=no username@your-timeweb-server 'sudo docker rm instabox-bot || true'
      - name: Pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@your-ec2-instance-ip 'sudo docker pull ryhorkukharenkadev/instabox-bot:latest'
      - name: SSH into Timeweb and deploy Docker image
        run: |
          ssh -o StrictHostKeyChecking=no username@your-timeweb-server 'docker run -d -p 3000:3000 ryhorkukharenkadev/instabox-bot:latest'